[package]
name = "vertex_finder"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
text_io = "0.1.9"
rand = "0.8.4"
colour = "0.6.0"
# colorful="0.2.1"
geo = "0.18.0"

