language: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
